// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ntTV7Oy8lbOmh2iMwEjjjlKnczpioLs',
    appId: '1:736705170233:web:2c20c05a36e4d1610af6e8',
    messagingSenderId: '736705170233',
    projectId: 'auth-module-d91f4',
    authDomain: 'auth-module-d91f4.firebaseapp.com',
    storageBucket: 'auth-module-d91f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqg3CL1sCc7mYi2zNVGn7IRXPA4laVi0',
    appId: '1:736705170233:android:c40c182b80b03a3b0af6e8',
    messagingSenderId: '736705170233',
    projectId: 'auth-module-d91f4',
    storageBucket: 'auth-module-d91f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxvdAML1WIkCzj0ghllxFDDy9Ihctqo0',
    appId: '1:736705170233:ios:17cccefdbf4185870af6e8',
    messagingSenderId: '736705170233',
    projectId: 'auth-module-d91f4',
    storageBucket: 'auth-module-d91f4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAutentikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgxvdAML1WIkCzj0ghllxFDDy9Ihctqo0',
    appId: '1:736705170233:ios:17cccefdbf4185870af6e8',
    messagingSenderId: '736705170233',
    projectId: 'auth-module-d91f4',
    storageBucket: 'auth-module-d91f4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAutentikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7ntTV7Oy8lbOmh2iMwEjjjlKnczpioLs',
    appId: '1:736705170233:web:60bf2eb96921e2d20af6e8',
    messagingSenderId: '736705170233',
    projectId: 'auth-module-d91f4',
    authDomain: 'auth-module-d91f4.firebaseapp.com',
    storageBucket: 'auth-module-d91f4.firebasestorage.app',
  );
}
